version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: fin_dir_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306" # чтобы не конфликтовать с локальным MySQL (если есть)

  wordpress:
    image: wordpress:php8.2-apache
    container_name: fin_dir_wp
    depends_on:
      - db
    restart: always
    ports:
      - "8000:80"   # сайт будет доступен на http://localhost:8000
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
    volumes:
      # Монтируем только wp-content, ядро WP живёт внутри контейнера
      - ./wp-content:/var/www/html/wp-content

  site:
    container_name: fin_dir_site
    build:
      context: ./site
      args:
        SITE_BASE_IMAGE: vashfindir-site-php-apache-base:8.3-bookworm
    restart: always
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      APP_SECRET: dev-site-secret
      DEFAULT_URI: http://localhost:8001
    volumes:
      - ./site:/var/www/html
      - site_vendor:/var/www/html/vendor
      - site_var:/var/www/html/var
    ports:
      - "8001:80"

  site-php-cli:
    profiles:
      - cli
    container_name: fin_dir_site_php_cli
    build:
      context: ./site
      args:
        SITE_BASE_IMAGE: vashfindir-site-php-apache-base:8.3-bookworm
    working_dir: /var/www/html
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      APP_SECRET: dev-site-secret
      DEFAULT_URI: http://localhost:8001
    volumes:
      - ./site:/var/www/html
      - site_vendor:/var/www/html/vendor
      - site_var:/var/www/html/var

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fin_dir_pma
    depends_on:
      - db
    restart: always
    ports:
      - "8080:80"   # phpMyAdmin будет на http://localhost:8080
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_pass

volumes:
  db_data:
  site_vendor:
  site_var:
