<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Статьи блога (модуль Publication). Только создание таблицы -- безопасно для данных.
 */
final class Version20260923072155 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create publication_post table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE publication_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, slug VARCHAR(150) NOT NULL, excerpt VARCHAR(300) DEFAULT NULL, body TEXT NOT NULL, status VARCHAR(16) NOT NULL, meta_title VARCHAR(70) DEFAULT NULL, meta_description VARCHAR(170) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX publication_post_status_idx ON publication_post (status)');
        $this->addSql('CREATE UNIQUE INDEX publication_post_slug_uniq ON publication_post (slug)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE publication_post');
    }
}
