<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Таблица кейсов клиентов (модуль ClientCase).
 */
final class Version20261004140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create client_case table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE client_case (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(120) NOT NULL, industry VARCHAR(32) NOT NULL, title VARCHAR(200) NOT NULL, problem TEXT NOT NULL, result_value VARCHAR(60) NOT NULL, result_label VARCHAR(160) NOT NULL, tags JSON NOT NULL, task TEXT DEFAULT NULL, steps JSON NOT NULL, metrics JSON NOT NULL, source VARCHAR(160) DEFAULT NULL, featured BOOLEAN NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX client_case_status_idx ON client_case (status)');
        $this->addSql('CREATE INDEX client_case_industry_idx ON client_case (industry)');
        $this->addSql('CREATE UNIQUE INDEX client_case_slug_uniq ON client_case (slug)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE client_case');
    }
}
