<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Обращения с форм сайта (модуль Lead) и заметки к ним. Только создание таблиц.
 */
final class Version20260923105607 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create lead_lead and lead_note tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE lead_lead (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, submission_id UUID NOT NULL, form_key VARCHAR(32) NOT NULL, name VARCHAR(100) NOT NULL, contact VARCHAR(200) NOT NULL, contact_normalized VARCHAR(200) NOT NULL, contact_type VARCHAR(16) NOT NULL, task TEXT DEFAULT NULL, answers JSON NOT NULL, page_url VARCHAR(500) DEFAULT NULL, referrer VARCHAR(500) DEFAULT NULL, utm JSON NOT NULL, consent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consent_version VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL, spam_reason VARCHAR(32) DEFAULT NULL, next_contact_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notification_error VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT DEFAULT 1 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX lead_lead_status_idx ON lead_lead (status)');
        $this->addSql('CREATE INDEX lead_lead_contact_idx ON lead_lead (contact_normalized)');
        $this->addSql('CREATE INDEX lead_lead_created_idx ON lead_lead (created_at)');
        $this->addSql('CREATE UNIQUE INDEX lead_lead_submission_uniq ON lead_lead (submission_id)');
        $this->addSql('CREATE TABLE lead_note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lead_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2E4BBFCE55458D ON lead_note (lead_id)');
        $this->addSql('ALTER TABLE lead_note ADD CONSTRAINT FK_2E4BBFCE55458D FOREIGN KEY (lead_id) REFERENCES lead_lead (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE lead_note DROP CONSTRAINT FK_2E4BBFCE55458D');
        $this->addSql('DROP TABLE lead_lead');
        $this->addSql('DROP TABLE lead_note');
    }
}
