controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

publication_controllers:
  resource:
    path: ../src/Publication/Controller/
    namespace: App\Publication\Controller
  type: attribute

admin_controllers:
  resource:
    path: ../src/Admin/Controller/
    namespace: App\Admin\Controller
  type: attribute
